version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
      - frontend

  backend:
    build: ./backend
    volumes:
      - static_volume:/code/staticfiles
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - static_volume:/usr/src/app/public

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
