version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/.next
    ports:
      - "3000:3000"
    env_file: .env

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env


volumes:
  postgres_data:
