# Generated by Django 4.2.7 on 2023-12-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('remote', models.CharField(max_length=50)),
                ('timing', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('responsibilities', models.JSONField(default=list)),
                ('required_qualifications', models.JSONField(default=list)),
                ('industry', models.CharField(max_length=100)),
                ('work_experience', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('job_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_details', to='app.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='app.jobpost')),
            ],
        ),
    ]
